name: Backend CI (CodeBuild Runner)

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/back.build.yml'
  # pull_request:
  #   paths:
  #     - 'frontend/**'

jobs:
  build-backend:
    runs-on: codebuild-blog-backend-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag (timestamp)
        run: |
          echo $(date +'%Y%m%d-%H%M')
          echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: backend
        run: |
          echo "Using tag: ${IMAGE_TAG}"
          docker build -t production-backend:${IMAGE_TAG} .

      - name: Tag and push image to ECR
        working-directory: backend
        run: |
          REPOSITORY=production/backend

          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${REPOSITORY}

          docker tag production/backend:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}

          docker push ${ECR_URI}:${IMAGE_TAG}

          docker tag ${ECR_URI}:${IMAGE_TAG} ${ECR_URI}:latest
          docker push ${ECR_URI}:latest
